export type PaletteId =
  | "padrao"
  | "escuro"
  | "rosa"
  | "lavanda"
  | "esmeralda"
  | "oceano"
  | "ambar";

export type Palette = {
  id: PaletteId;
  name: string;
  swatch: string;
  accent: string;
  sidebar: string;
  sidebarForeground: string;
  sidebarMuted: string;
  sidebarActive: string;
  paper: string;
  surface: string;
  surfaceMuted: string;
  surfaceForeground: string;
  line: string;
  brass: string;
  brassLight: string;
  wine: string;
  moss: string;
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  popover: string;
  popoverForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accentBg: string;
  accentFg: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  ring: string;
};

export const palettes: Palette[] = [
  {
    id: "padrao",
    name: "Padrão",
    swatch: "linear-gradient(135deg, #1e40af 0%, #b8860b 50%, #f0d060 100%)",
    accent: "#8c6425",
    sidebar: "#16233a",
    sidebarForeground: "#d7d2c2",
    sidebarMuted: "#b9b29b",
    sidebarActive: "#f1ede0",
    paper: "#f6f3ea",
    surface: "#ffffff",
    surfaceMuted: "#ede9dd",
    surfaceForeground: "#16233a",
    line: "#d9d2bf",
    brass: "#9a6a22",
    brassLight: "#d9b372",
    wine: "#7a2e2e",
    moss: "#4b6b4e",
    background: "#f6f3ea",
    foreground: "#1a1a1a",
    card: "#ffffff",
    cardForeground: "#16233a",
    popover: "#ffffff",
    popoverForeground: "#16233a",
    primary: "#8c6425",
    primaryForeground: "#ffffff",
    secondary: "#ede9dd",
    secondaryForeground: "#1f3350",
    muted: "#ede9dd",
    mutedForeground: "#5b5548",
    accentBg: "#ede9dd",
    accentFg: "#16233a",
    destructive: "#7a2e2e",
    destructiveForeground: "#ffffff",
    border: "#d9d2bf",
    input: "#d9d2bf",
    ring: "#8c6425",
  },
  {
    id: "escuro",
    name: "Escuro",
    swatch: "linear-gradient(135deg, #000000 0%, #1a1a1a 50%, #333333 100%)",
    accent: "#9a6a22",
    sidebar: "#070707",
    sidebarForeground: "#e8e2d3",
    sidebarMuted: "#aaa394",
    sidebarActive: "#ffffff",
    paper: "#111111",
    surface: "#171717",
    surfaceMuted: "#202020",
    surfaceForeground: "#f4f1e9",
    line: "#333333",
    brass: "#9a6a22",
    brassLight: "#d9b372",
    wine: "#7a2e2e",
    moss: "#4b6b4e",
    background: "#111111",
    foreground: "#f4f1e9",
    card: "#1a1a1a",
    cardForeground: "#f4f1e9",
    popover: "#1a1a1a",
    popoverForeground: "#f4f1e9",
    primary: "#9a6a22",
    primaryForeground: "#ffffff",
    secondary: "#262626",
    secondaryForeground: "#f4f1e9",
    muted: "#262626",
    mutedForeground: "#b8b1a2",
    accentBg: "#262626",
    accentFg: "#f4f1e9",
    destructive: "#7a2e2e",
    destructiveForeground: "#ffffff",
    border: "#333333",
    input: "#333333",
    ring: "#9a6a22",
  },
  {
    id: "rosa",
    name: "Rosa",
    swatch: "linear-gradient(135deg, #e93577 0%, #f8c9d8 50%, #fefefe 100%)",
    accent: "#e93577",
    sidebar: "#fadce3",
    sidebarForeground: "#091d3e",
    sidebarMuted: "#847880",
    sidebarActive: "#e93577",
    paper: "#fef8f9",
    surface: "#ffffff",
    surfaceMuted: "#fef1f5",
    surfaceForeground: "#091d3e",
    line: "#f8c9d8",
    brass: "#e93577",
    brassLight: "#f8c9d8",
    wine: "#be185d",
    moss: "#059669",
    background: "#fffefe",
    foreground: "#091d3e",
    card: "#fffefe",
    cardForeground: "#091d3e",
    popover: "#fffefe",
    popoverForeground: "#091d3e",
    primary: "#e93577",
    primaryForeground: "#ffffff",
    secondary: "#fef1f5",
    secondaryForeground: "#091d3e",
    muted: "#fef1f5",
    mutedForeground: "#847880",
    accentBg: "#fef1f5",
    accentFg: "#e93577",
    destructive: "#be185d",
    destructiveForeground: "#ffffff",
    border: "#f8c9d8",
    input: "#f8c9d8",
    ring: "#e65288",
  },
  {
    id: "lavanda",
    name: "Lavanda",
    swatch: "linear-gradient(135deg, #7c3aed 0%, #c4b5fd 50%, #f5f3ff 100%)",
    accent: "#7c3aed",
    sidebar: "#ebe7fc",
    sidebarForeground: "#091d3e",
    sidebarMuted: "#8b7fb8",
    sidebarActive: "#7c3aed",
    paper: "#f7f5fd",
    surface: "#ffffff",
    surfaceMuted: "#ede9fe",
    surfaceForeground: "#091d3e",
    line: "#c4b5fd",
    brass: "#7c3aed",
    brassLight: "#c4b5fd",
    wine: "#6d28d9",
    moss: "#059669",
    background: "#faf9ff",
    foreground: "#091d3e",
    card: "#faf9ff",
    cardForeground: "#091d3e",
    popover: "#faf9ff",
    popoverForeground: "#091d3e",
    primary: "#7c3aed",
    primaryForeground: "#ffffff",
    secondary: "#ede9fe",
    secondaryForeground: "#091d3e",
    muted: "#ede9fe",
    mutedForeground: "#5b5078",
    accentBg: "#ede9fe",
    accentFg: "#7c3aed",
    destructive: "#6d28d9",
    destructiveForeground: "#ffffff",
    border: "#c4b5fd",
    input: "#c4b5fd",
    ring: "#7c3aed",
  },
  {
    id: "esmeralda",
    name: "Esmeralda",
    swatch: "linear-gradient(135deg, #059669 0%, #6ee7b7 50%, #ecfdf5 100%)",
    accent: "#059669",
    sidebar: "#d5f3e4",
    sidebarForeground: "#091d3e",
    sidebarMuted: "#6ee7b7",
    sidebarActive: "#059669",
    paper: "#f4fcf7",
    surface: "#ffffff",
    surfaceMuted: "#d1fae5",
    surfaceForeground: "#091d3e",
    line: "#a7f3d0",
    brass: "#059669",
    brassLight: "#6ee7b7",
    wine: "#dc2626",
    moss: "#065f46",
    background: "#f9fffc",
    foreground: "#091d3e",
    card: "#f9fffc",
    cardForeground: "#091d3e",
    popover: "#f9fffc",
    popoverForeground: "#091d3e",
    primary: "#059669",
    primaryForeground: "#ffffff",
    secondary: "#d1fae5",
    secondaryForeground: "#091d3e",
    muted: "#d1fae5",
    mutedForeground: "#3d6b5a",
    accentBg: "#d1fae5",
    accentFg: "#059669",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#a7f3d0",
    input: "#a7f3d0",
    ring: "#059669",
  },
  {
    id: "oceano",
    name: "Oceano",
    swatch: "linear-gradient(135deg, #0284c7 0%, #7dd3fc 50%, #f0f9ff 100%)",
    accent: "#0284c7",
    sidebar: "#daedfb",
    sidebarForeground: "#091d3e",
    sidebarMuted: "#7dd3fc",
    sidebarActive: "#0284c7",
    paper: "#f3f9fe",
    surface: "#ffffff",
    surfaceMuted: "#e0f2fe",
    surfaceForeground: "#091d3e",
    line: "#a5d8f5",
    brass: "#0284c7",
    brassLight: "#7dd3fc",
    wine: "#dc2626",
    moss: "#059669",
    background: "#f9fcff",
    foreground: "#091d3e",
    card: "#f9fcff",
    cardForeground: "#091d3e",
    popover: "#f9fcff",
    popoverForeground: "#091d3e",
    primary: "#0284c7",
    primaryForeground: "#ffffff",
    secondary: "#e0f2fe",
    secondaryForeground: "#091d3e",
    muted: "#e0f2fe",
    mutedForeground: "#4a7a9b",
    accentBg: "#e0f2fe",
    accentFg: "#0284c7",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#a5d8f5",
    input: "#a5d8f5",
    ring: "#0284c7",
  },
  {
    id: "ambar",
    name: "Âmbar",
    swatch: "linear-gradient(135deg, #d97706 0%, #fbbf24 50%, #fffbeb 100%)",
    accent: "#d97706",
    sidebar: "#fce9bd",
    sidebarForeground: "#091d3e",
    sidebarMuted: "#fbbf24",
    sidebarActive: "#d97706",
    paper: "#fdf9f1",
    surface: "#ffffff",
    surfaceMuted: "#fef3c7",
    surfaceForeground: "#091d3e",
    line: "#fcd68d",
    brass: "#d97706",
    brassLight: "#fbbf24",
    wine: "#92400e",
    moss: "#065f46",
    background: "#fffcf9",
    foreground: "#091d3e",
    card: "#fffcf9",
    cardForeground: "#091d3e",
    popover: "#fffcf9",
    popoverForeground: "#091d3e",
    primary: "#d97706",
    primaryForeground: "#ffffff",
    secondary: "#fef3c7",
    secondaryForeground: "#091d3e",
    muted: "#fef3c7",
    mutedForeground: "#6b5a30",
    accentBg: "#fef3c7",
    accentFg: "#d97706",
    destructive: "#92400e",
    destructiveForeground: "#ffffff",
    border: "#fcd68d",
    input: "#fcd68d",
    ring: "#d97706",
  },
];

export function getPaletteStyles(palette: Palette): React.CSSProperties {
  return {
    "--tenant-sidebar": palette.sidebar,
    "--tenant-sidebar-foreground": palette.sidebarForeground,
    "--tenant-sidebar-muted": palette.sidebarMuted,
    "--tenant-sidebar-active": palette.sidebarActive,
    "--tenant-paper": palette.paper,
    "--tenant-surface": palette.surface,
    "--tenant-subtask-surface":
      palette.id === "escuro"
        ? `color-mix(in srgb, #ffffff 7%, ${palette.surface})`
        : `color-mix(in srgb, ${palette.brass} 9%, ${palette.surface})`,
    "--tenant-surface-muted": palette.surfaceMuted,
    "--tenant-surface-foreground": palette.surfaceForeground,
    "--tenant-line": palette.line,
    "--tenant-brass": palette.brass,
    "--tenant-brass-light": palette.brassLight,
    "--tenant-logo-meu": palette.id === "padrao" ? "#091d3e" : palette.id === "escuro" ? "#ffffff" : "#091d3e",
    "--tenant-logo-judi": palette.id === "padrao" ? "#b08b59" : palette.id === "escuro" ? "#ffffff" : palette.brass,
    "--tenant-logo-scales": palette.id === "padrao" ? "#091d3e" : palette.id === "escuro" ? "#ffffff" : palette.brass,
    "--tenant-wine": palette.wine,
    "--tenant-moss": palette.moss,
    "--color-background": palette.background,
    "--color-foreground": palette.foreground,
    "--color-card": palette.card,
    "--color-card-foreground": palette.cardForeground,
    "--color-popover": palette.popover,
    "--color-popover-foreground": palette.popoverForeground,
    "--color-primary": palette.primary,
    "--color-primary-foreground": palette.primaryForeground,
    "--color-secondary": palette.secondary,
    "--color-secondary-foreground": palette.secondaryForeground,
    "--color-muted": palette.muted,
    "--color-muted-foreground": palette.mutedForeground,
    "--color-accent": palette.accentBg,
    "--color-accent-foreground": palette.accentFg,
    "--color-destructive": palette.destructive,
    "--color-destructive-foreground": palette.destructiveForeground,
    "--color-border": palette.border,
    "--color-input": palette.input,
    "--color-ring": palette.ring,
  } as React.CSSProperties;
}
